# Generated by Django 4.1.1 on 2022-09-23 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Макс. 24 символа', max_length=24, verbose_name='название')),
                ('descr', models.CharField(blank=True, help_text='Макс. 140 символов', max_length=140, null=True, verbose_name='описание')),
                ('is_published', models.BooleanField(default=False, verbose_name='публикация')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='род. категория')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'db_table': 'app_categories',
                'ordering': ('is_published', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Макс. 36 символов', max_length=36, null=True, verbose_name='название')),
                ('descr', models.CharField(blank=True, help_text='Макс. 140 символов', max_length=140, null=True, verbose_name='описание')),
                ('article', models.CharField(help_text='Макс. 16 символов', max_length=16, unique=True, verbose_name='артикул')),
                ('is_published', models.BooleanField(default=False, verbose_name='публикация')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Макс. 999999.99', max_digits=8, verbose_name='цена')),
                ('count', models.PositiveSmallIntegerField(default=0, verbose_name='количество')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.category', verbose_name='категория')),
            ],
            options={
                'db_table': 'app_products',
            },
        ),
    ]
