# Generated by Django 4.1.1 on 2022-09-23 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('price', 'title', 'article'), 'verbose_name': ('товар',), 'verbose_name_plural': ('товары',)},
        ),
        migrations.AlterModelTable(
            name='product',
            table=('app_products',),
        ),
    ]
